apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: home-vlan-subnet
spec:
  hostname: home-vlan-subnet
  subnetRouter:
    advertiseRoutes:
      - "10.0.10.0/24"
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: exit-node
spec:
  hostname: rwade-exit-node
  exitNode: true
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: streaming
spec:
  appConnector: {}
  replicas: 2
  tags:
    - "tag:hbo-connector"
    - "tag:netflix-connector"
