apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:UXyhGS8=,iv:bhKPFqq6eZV8jmjT07RdyRSpbAOINBuvZFulH6ShdoA=,tag:lJ2B98YQmPyxsqy8Dw22jQ==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:vxYcHae3no/EHfwrkhXNWAkG,iv:VRAUn+rPW+N7qZu3j259zsslKNcdZ17RpTacv/KCfOs=,tag:s5ni7/hGhpLZt9wb3HG/LQ==,type:str]
sops:
  age:
    - recipient: age12mypajrzr7dde93e3kyrxfd03vfarlqm79myg4dyndlmdlgxd90su39t43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBER1V1bk1jdEl2Qkh1cWt1
        NWJyci9lVDh2Zk9rYXNqZkRJRVEvYXdlT1VvCmM2andvL3E2MTVIQ3pNOTRpOUVU
        aUVDL0laQ3NIRnl2TzRvSVhuUUNPeUUKLS0tIFNPUy9CWHpUWU9UbmtYRmRBODVB
        U3NrOWRRaUgwelU1d0dFWGN6WncyRlEK8Luxro95mA3f9043IeRlGh7dGOnliR5s
        aGPwjjtH8M1LHtqpl/pVOSa3StZXTiEFpR9KNgiDEKCArmjxGL5A7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-06T16:18:13Z"
  mac: ENC[AES256_GCM,data:5orUYsdazC+enw/HSfWip4UwRR2Ep9PnTLY0ldL3YJjvQ5m1UZ2/n0rvd/vsZHDld3cC5LbxDyTrFMLRqBgtqyst2hX8g6xfhsslPxEL8eDyDGGaahmyhtodZF3tIbuNSnBdVs6wnTuvIZcDK3oj678jJ7f+9g+pHl+8WEcHEjQ=,iv:+MSOmtpD7q0aoQblolNMPrPLLuwKRYkSoYUVFsbSCiE=,tag:CVLTfgiKKTD3amO34xO4SQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
