---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: enable-backend-tls
  namespace: default
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: omada
      sectionName: https
  validation:
    caCertificateRefs:
      - name: casadewade-com-production-tls
        namespace: network
        kind: Secret
    hostname: "omada.${SECRET_DOMAIN}"
