---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: tls-backend
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: omada.omada.svc.cluster.local
        port: 443
  tls:
    insecureSkipVerify: true
# ---
# apiVersion: gateway.networking.k8s.io/v1alpha3
# kind: BackendTLSPolicy
# metadata:
#   name: enable-backend-tls
#   namespace: default
# spec:
#   targetRefs:
#     - group: ""
#       kind: Service
#       name: omada
#       sectionName: https
#   validation:
#     caCertificateRefs:
#       - name: network/casadewade-com-production-tls
#         group: ""
#         kind: Secret
#     hostname: "omada.${SECRET_DOMAIN}"
